version: '3.8'

services:
  caddy:
    image: caddy:2.4.6
    container_name: caddy_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./site:/usr/share/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  go_server:
    build: .
    container_name: go_server
    ports:
      - "8080:8080"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"


volumes:
  caddy_data:
  caddy_config: