version: '3.8'
services:
  caddy:
    image: caddy:2.4.6
    container_name: caddy_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./site:/usr/share/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config: